### ISSUE TITLE
CogVideX A100 多卡性能异常

### ISSUE THREAD

**Issue by gttiankai** [NUS-HPC-AI-Lab/VideoSys#189]
你好，首先非常感谢开源的 VideoSys 项目，提供了非常好的推理加速框架。

我在使用 VideoSys 推理 CogVideoX （2b/5b）模型遇到一些问题，直接使用 examples/cogvideox/sample.py  进行推理，使用 pab 模型，没有改生成视频的参数，单卡 A100 的性能是 172 second，使用 8 卡（设置 num_gpus = 8），推理时间的耗时也是 178 second 左右。从推理性能来看使用 8 卡推理和使用单卡推理，并没有性能上的提升。另外使用 examples/cogvideox/sample.py  中的 base 模型进行推理，单卡和 8 卡的性能也是位置在 227 second 左右，也没有性能上的提升。

测试环境如下
使用的测试代码：当前 master 分支最新代码： commit id: ba44ccd4
显卡：A100，CUDA Version: 12.1， 
torch : 2.2.2
测试脚本：examples/cogvideox/sample.py
统计耗时的方案，直接修改 examples/cogvideox/sample.py 的代码，修改的代码示例如下：
```
prompt = "A man is eating at a table.
start_time = time.perf_counter()  
video = engine.generate(prompt).video[0]  
cost_time = time.perf_counter() - start_time 
print("Inference {} cost time: {:.3f} seconds".format(model, cost_time))
````

请问这个问题应该如何解决？

**Comment by oahzxl** [comment]
hi the method to use parallel is to set num_gpus=8. but currently we don't support parallel for cogvideo yet. will update very soon.

**Comment by oahzxl** [comment]
fixed here #193

**Comment by gttiankai** [comment]
@oahzxl 感谢回复，我目前测试了下 CogVideo 的多卡的性能情况，目前发现对 CogVideo 的多卡的支持有问题，我同样使用examples/cogvideox/sample.py  进行推理，设置 num_gpus=2, 模型是用 "THUDM/CogVideoX-2b"，推理会报错
```
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.19.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 0 and rank 1 both on CUDA device e000
```
很奇怪的报错。

**Comment by oahzxl** [comment]
how do you launc? we use python to launch instead of torchrun
________________________________
发件人: lucasktian ***@***.***>
发送时间: Friday, September 6, 2024 5:20:38 PM
收件人: NUS-HPC-AI-Lab/VideoSys ***@***.***>
抄送: Xuanlei Zhao ***@***.***>; Mention ***@***.***>
主题: Re: [NUS-HPC-AI-Lab/VideoSys] CogVideX A100 多卡性能异常 (Issue #189)


@oahzxl<https://github.com/oahzxl> 感谢回复，我目前测试了下 CogVideo 的多卡的性能情况，目前发现对 CogVideo 的多卡的支持有问题，我同样使用examples/cogvideox/sample.py 进行推理，设置 num_gpus=2, 模型是用 "THUDM/CogVideoX-2b"，推理会报错

torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.19.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 0 and rank 1 both on CUDA device e000


很奇怪的报错。

―

**Comment by gttiankai** [comment]
1. 目前 launch使用的是 python 命令，没有使用 torchrun 命令。推理使用的命令式是： 
```
python examples/cogvideox/sample.py 
``` 
3. 目前上面的在多卡上推理报错的问题已经解决了，推理时需要将 'cpu_offload' 设置为 ‘False’

**Comment by oahzxl** [comment]
yeah! the memory efficient inference is only for single gpu.

**Comment by oahzxl** [comment]
close due to inactive
